### ISSUE TITLE
Angular CLI Usage

### ISSUE THREAD

**Issue by baruchvlz** [Gbuomprisco/ng2-material-dropdown#12]
Just putting this here for anyone wondering, this is how i made the dropdown components work with Angular CLI:

*app.module.ts*
```javascript
...
import { MaterialModule, ... } from '@angular/material';
import { Ng2DropdownModule } from 'ng2-material-dropdown';

@NgModule({
  ...,
  imports: [
    ...,
    Ng2DropdownModule 
  ]
})
```

*navbar.component.html*
```html
<md-toolbar color="" class="nav-bar">
  <div class="nav-bar__left">
    <button md-icon-button>
        <md-icon class="default">menu</md-icon>
    </button>
  </div>
  <div class="nav-bar__right">
    <ng2-dropdown>
      <ng2-dropdown-button>
        <md-icon class="default">notifications_none</md-icon>
      </ng2-dropdown-button>
      <ng2-dropdown-menu>
        <ng2-menu-item>
          Item
        </ng2-menu-item>
      </ng2-dropdown-menu>
    </ng2-dropdown>
  </div>
</md-toolbar>
```

The only thing I couldn't get to work was the divider
> Unhandled Promise rejection: Template parse errors: 'ng2-menu-divider' is not a known element:

**Comment by sufian07** [comment]
Same for me, `Unhandled Promise rejection: Template parse errors: 'ng2-menu-divider' is not a known element:`

**Comment by Gbuomprisco** [comment]
Hi @sufian07, @baruchvlz 

Thanks, I've updated the Readme (after a long time!).

Please use `ng2-menu-divider` as a class instead, not as element. :)
