### ISSUE TITLE
 Unexpected module 'Ng2DropdownModule' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by phuongnc** [Gbuomprisco/ng2-material-dropdown#20]

**Comment by rajshrimohanks** [comment]
The module needs to be compiled with ngc to generate *.metadata.json files. This issue also leads to the issue here: https://github.com/Gbuomprisco/ng2-tag-input/issues/98

**Comment by Gbuomprisco** [comment]
Hi, this should now be working
