### ISSUE TITLE
Request ng2-dropdown-menu

### ISSUE THREAD

**Issue by suplik10** [Gbuomprisco/ng2-material-dropdown#24]
Hi, 

at first time I want to say big thx for your component. Its awesome! :)

I have 2 requests, which I need in my project :(

1.st can u add OUtput emit event on ng2-dropdown-menu to method hide()? This event will be emited after click on ng2-dropdown-backdrop. I belive it helps a lot of users! 

2.nd can u add boolean switch to enable/disable method updatePosition called from Ng2Dropdown after scroll window ? (@HostListener('window:scroll')) (Problem with dropdown is when we using dropdown on the middle of page and dropdown has a lot of items, all dropdown is automatic switched on the top of page but still isnt displayed well. 

THX you very much, I belive this is a very positive update for your component and work for u is couple of minutes! :)

**Comment by Gbuomprisco** [comment]
Hi @suplik10,

Do you mean the output even `onHide()`? It should be there if you meant that :)

I can add an option for the 2nd point. I believe a few users requested it

**Comment by Gbuomprisco** [comment]
Added an option for that in the latest release :)
