### ISSUE TITLE
Possibility to apply custom styling

### ISSUE THREAD

**Issue by nitimmerman** [Gbuomprisco/ng2-material-dropdown#25]
Hi there,

First of all, thanks for creating and publishing this component!

I'm using this component via the ng2-tag-input but i'm having issues with the styling caused by a this padding rule in your style.scss of the menu-item .ng2-menu-item {
    font-family: "Roboto", "Helvetica Neue", Helvetica, Arial;

    padding: 0.3em 1.25rem
the dropdown looks like this by now:
![image](https://cloud.githubusercontent.com/assets/20041096/21566440/5d5b7eb4-cea3-11e6-8303-f0d1d20b87b2.png)

I'm not totally sure what is causing this awfull layout but if i remove the vertical padding (via the developer tools in the browser) the scrollbar disappears and it looks normal again.

Do you have any recommendations on how to prevent this issue?
Or could you style the menu item via sccs variables so i can override them?

Many thanks

**Comment by Gbuomprisco** [comment]
Hi @nitimmerman,

Thanks for reporting this and sorry for the delayed response but Github is not notifying me for new issues. What browser/OS are you using? Unfortunately you cannot overwrite it as it it's encapsulated.

**Comment by nitimmerman** [comment]
Hi @Gbuomprisco,
No problem, I'm using Google Chrome. Just investigated a bit better and found that the available space is just a little bit too small. please see the attached screenshot.https://github.com/Gbuomprisco/ng2-material-dropdown/issues/25#issuecomment-271169532
removing the height=48px; or removing the height or line-height rules also removes the scrollbar but then the text gets top/bottom aligned.

**Comment by srkela** [comment]
Hi @Gbuomprisco,

Same issue here, seem to have something with Bootstrap CSS. When I remove Bootstrap from project, layout is not broken any more.

**Comment by roanhawkeye** [comment]
Hi guys, 

You can override any css class from src/styles.css file, if your using angular-cli , I just did in order to increase the max-width for the dropdown-button of class '.ng2-dropdown-button
' .

hope this could help you.

**Comment by sebastientromp** [comment]
Hey, I'm having the same issue. I've tried overloading the `.ng2-dropdown-button` class in my parent component, but it isn't picked (I suppose it's because of encapsulation).

@roanhawkeye did you do anything else to make this work?

Alternatively, @nitimmerman, is there a way to remove encapsulation from the component?

Thanks!

**Comment by gangsthub** [comment]
@sebastientromp you can use global styles.

@nitimmerman, as long as you solved the issue by yourself, is it ok to close it?

**Comment by nitimmerman** [comment]
@gangsthub Currently I'm not using this control anymore. mainly because the styling doesn't play well with the styling of the rest of the application. So OK to me to close this issue
