### ISSUE TITLE
how to set a preselected value in the drop down 

### ISSUE THREAD

**Issue by AngularTx** [Gbuomprisco/ng2-material-dropdown#27]
Hi ,

I am currently working on angular version 2.10 . The application is being developed in IE browser. 
Does this plugin work well on IE also ?
How do i have a preselected value shown in the drop down .
Is there flexibility in changing the appearance of the  drop down to suit our application design standards?
Is there any search option in drop down provided ?

**Comment by Gbuomprisco** [comment]
Hi @AngularTx,

Sorry, pretty much none of the above applies..
