### ISSUE TITLE
Dropdown have no scrollbar

### ISSUE THREAD

**Issue by pschalk** [Gbuomprisco/ng2-material-dropdown#35]
Hi, 

I've just upgraded from ng2-tag-input 1.3.5 to ngx-chips 1.5.0 + 0.7.9-beta-3 (also tried with 0.7.7). 

Now I'm facing the problem that my dropdowns don't have a scrollbar anymore, the component just shows a very long list of all autocomplete entries. 

Used code: 

```
<div class="form-group">
  <label>Place Type</label>
              <tag-input name="placeType" [(ngModel)]='placeTypes'
                         [placeholder]="placeTypesOptions.placeholder"
                         [secondaryPlaceholder]="placeTypesOptions.secondaryPlaceholder"
                         [separatorKeys]="placeTypesOptions.separatorKeys"
                         [onlyFromAutocomplete]="true">
                <tag-input-dropdown
                  [showDropdownIfEmpty]="true"
                  [autocompleteItems]="placeTypesAutoComplete">
                </tag-input-dropdown>
  </tag-input>
</div>
```
Here is also a picture:

<img width="301" alt="screen shot 2017-08-13 at 14 55 34" src="https://user-images.githubusercontent.com/8512329/29249906-0c68f05c-8039-11e7-8528-6f3f3a6029db.png">

Maybe just some wrong configuration? I've already searched in the issues + docs, but it looks like the configurations is correct (and I'm the only one who have this porblem^^)

Thanks,
Patrick

**Comment by Gbuomprisco** [comment]
Hi @pschalk,

this is definitely a bug, the config is OK and I can reproduce. Will have a look soon

**Comment by pschalk** [comment]
Cool, thanks for your fast reply + help :)

**Comment by msouf** [comment]
Hello,

I am facing the same problem as pschalk describe with the last version of ngx-chips 1.5.2.  The dropdown has nor a fixed height and neither a scrollbar. 

Please let us know if there is a workaround while waiting for the correction.

Thank you
Soufiane

**Comment by Gbuomprisco** [comment]
v 1.7.10 released :)

**Comment by pschalk** [comment]
You mean 0.7.10 :D I've tested it, bug is fixed, many thanks! :)
