### ISSUE TITLE
I want the dropdown to render the first dropdown menu item by default.

### ISSUE THREAD

**Issue by ishandutta2007** [Gbuomprisco/ng2-material-dropdown#38]
I dont want a dropdown button titile like "Show" etc. I want the dropdown to render the first dropdown menu by default. How do I do that ?
Secondly in that example, I found no matter dropdown menu  item I select it always shows the text within `<ng2-dropdown-button>`, why is it so and how can I change this to menu item selected ?

I started with the exact code shown in readme.

**Comment by Gbuomprisco** [comment]
Hi, this is a drop down and not a select component. You're looking for a select form.

**Comment by ishandutta2007** [comment]
Thanks, found your [select](https://github.com/Gbuomprisco/ng2-material-select) plugin, will comment there if I face any issues.

**Comment by Gbuomprisco** [comment]
it's not very updated, I am afraid it won't work with the latest angular
