### ISSUE TITLE
Module '"node_modules/ng2-material-dropdown/index"' has no exported member 'NG2_DROPDOWN_DIRECTIVES'.

### ISSUE THREAD

**Issue by FaberNa** [Gbuomprisco/ng2-material-dropdown#8]
When use this in my application with Angulr i see this error : 
`Module '"node_modules/ng2-material-dropdown/index"' has no exported member 'NG2_DROPDOWN_DIRECTIVES'.`

**Comment by Gbuomprisco** [comment]
Hi @FaberNa,

Sorry - the documentation is outdated. Try just importing the module `Ng2DropdownModule` in your module.

Reopen if still an issue :)
