### ISSUE TITLE
Dropdown menu element get left behind after dropdown is destroyed 

### ISSUE THREAD

**Issue by ZhangYiJiang** [Gbuomprisco/ng2-material-dropdown#9]
On https://github.com/Gbuomprisco/ng2-material-dropdown/blob/master/src/modules/components/menu/ng2-dropdown-menu.ts#L188, the dropdown menu element is attached to the body during initialization. This element is not removed when the component is destroyed, causing the element to be left behind in the DOM.

**Comment by Gbuomprisco** [comment]
Hi @ZhangYiJiang! This has been addressed in the latest version I just released.

Please reopen if still an issue.
